apiVersion: v1
kind: Pod
metadata:
  name: quotes-app-pod
  labels:
    app: quotes-app
spec:
  containers:
  - name: quotes-app
    image: sandiledocker/quotes_img
    envFrom:
    - configMapRef:
        name: quotes-config
    volumeMounts:
    - name: quotes-volume
      mountPath: /etc/quotes/quotes.txt
      subPath: quotes.txt
    ports:
    - containerPort: 5000
  volumes:
  - name: quotes-volume
    configMap:
      name: quotes-file-config
      items:
      - key: quotes.txt
        path: quotes.txt
      #  nodeSelector:
      # one-to-three-worker2: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: quotes-app-service
spec:
  selector:
    app: quotes-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: NodePort
